### ISSUE TITLE
Can't use built-in function in _spread

### ISSUE THREAD

**Issue by gengen1988** [twisterghost/gdash#11]
> `cannot use function/script name for a variable, using "ds_list_add"`

It seems like GM1 do not allow that. You may want to change the example in the script.

> ```
> /*
> @example
> _spread(ds_list_add, _arrayOf(listId, 1, 2, 3, 4));
> // => List now contains 1, 2, 3, 4
> */
> ```

**Comment by twisterghost** [comment]
👍 Good catch. Will update the example.

**Comment by twisterghost** [comment]
Addressed in 5da254a
